{% set name = "pysolr" %}
{% set version = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 127b4a2dd169234acb1586643a6cd1e3e94b917921e69bf569d7b2a2aa0ef409

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - requests >=2.9.1
    - setuptools

test:
  imports:
    - pysolr

about:
  home: https://github.com/django-haystack/pysolr/
  license: BSD-3-clause
  summary: Lightweight python wrapper for Apache Solr.
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cehbrecht
    - synapticarbors
